const players = [
  {
    accountId: "123123",
    name: "1vs70",
    calibrationGames: 2,
    calibrationWins: 0,
    calibrationLoses: 2,
    calibrationMmr: 5500,
    realMmr: 5900,
    totalGames: 2,
    totalWins: 0,
    totalLoses: 2,
    inhouseMmr: 5500,
  },
  {
    accountId: "123123",
    name: "A.Julius",
    calibrationGames: 10,
    calibrationWins: 4,
    calibrationLoses: 6,
    calibrationMmr: 2580,
    realMmr: 2980,
    totalGames: 12,
    totalWins: 5,
    totalLoses: 7,
    inhouseMmr: 2580,
  },
  {
    accountId: "123123",
    name: "actor-kyun",
    calibrationGames: 2,
    calibrationWins: 1,
    calibrationLoses: 1,
    calibrationMmr: 4290,
    realMmr: 4290,
    totalGames: 2,
    totalWins: 1,
    totalLoses: 1,
    inhouseMmr: 4290,
  },
  {
    accountId: "123123",
    name: "aeryj",
    calibrationGames: 1,
    calibrationWins: 1,
    calibrationLoses: 0,
    calibrationMmr: 4850,
    realMmr: 4650,
    totalGames: 1,
    totalWins: 1,
    totalLoses: 0,
    inhouseMmr: 4850,
  },
  {
    accountId: "123123",
    name: "Axeldota",
    calibrationGames: 6,
    calibrationWins: 4,
    calibrationLoses: 2,
    calibrationMmr: 4000,
    realMmr: 3600,
    totalGames: 6,
    totalWins: 4,
    totalLoses: 2,
    inhouseMmr: 4000,
  },
  {
    accountId: "123123",
    name: "Aykay",
    calibrationGames: 1,
    calibrationWins: 0,
    calibrationLoses: 1,
    calibrationMmr: 1560,
    realMmr: 1760,
    totalGames: 1,
    totalWins: 0,
    totalLoses: 1,
    inhouseMmr: 1760,
  },
  {
    accountId: "123123",
    name: "blazing bullshit",
    calibrationGames: 9,
    calibrationWins: 5,
    calibrationLoses: 4,
    calibrationMmr: 4360,
    realMmr: 4160,
    totalGames: 9,
    totalWins: 5,
    totalLoses: 4,
    inhouseMmr: 4360,
  },
  {
    accountId: "123123",
    name: "Blind",
    calibrationGames: 1,
    calibrationWins: 0,
    calibrationLoses: 1,
    calibrationMmr: 2240,
    realMmr: 2440,
    totalGames: 1,
    totalWins: 0,
    totalLoses: 1,
    inhouseMmr: 2240,
  },
  {
    accountId: "123123",
    name: "budds",
    calibrationGames: 10,
    calibrationWins: 7,
    calibrationLoses: 3,
    calibrationMmr: 4850,
    realMmr: 4050,
    totalGames: 22,
    totalWins: 14,
    totalLoses: 8,
    inhouseMmr: 4950,
  },
];
